import Head from 'next/head';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Tailwind CSS template</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1 className="h-screen text-3xl font-bold flex justify-center items-center">
                    Hello Tailwind CSS template!
                </h1>
            </main>
        </div>
    );
}
